# Generated by Django 6.0 on 2025-12-23 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_id', models.CharField(help_text='ID of the camera/device capturing the image', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ALERT', 'Alert (Risk Detected)')], default='PROCESSING', max_length=20)),
                ('risk_level', models.CharField(choices=[('HIGH', 'High Risk'), ('MEDIUM', 'Medium Risk'), ('LOW', 'Low Risk'), ('SAFE', 'Safe')], default='SAFE', max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='inspections/raw/%Y/%m/%d/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='inspections/processed/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('FOD', 'Foreign Object Debris'), ('BIRD', 'Bird/Wildlife'), ('CRACK', 'Crack'), ('POTHOLE', 'Pothole'), ('VEHICLE', 'Vehicle'), ('PERSON', 'Person'), ('OTHER', 'Other')], max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score from 0.0 to 1.0')),
                ('severity', models.CharField(choices=[('HIGH', 'High Risk'), ('MEDIUM', 'Medium Risk'), ('LOW', 'Low Risk'), ('SAFE', 'Safe')], default='LOW', max_length=10)),
                ('bbox_data', models.JSONField(default=dict, help_text="{'x': 0.5, 'y': 0.5, 'width': 0.1, 'height': 0.2}")),
                ('gemini_suggestion', models.TextField(blank=True, help_text='AI suggested solution for this hazard', null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='inspections.inspectionimage')),
            ],
        ),
    ]
