# Generated by Django 6.0 on 2025-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='inspections/videos/%Y/%m/%d/'),
        ),
    ]
