# Generated by Django 6.0 on 2025-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobject',
            name='object_type',
            field=models.CharField(choices=[('FOD', 'Foreign Object Debris'), ('BIRD', 'Bird/Wildlife'), ('CRACK', 'Crack'), ('POTHOLE', 'Pothole'), ('VEHICLE', 'Vehicle'), ('AIRCRAFT', 'Aircraft'), ('PERSON', 'Person'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
