# Generated by Django 6.0 on 2026-01-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_detectedobject_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='inspections/videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='inspectionimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='inspections/raw/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='inspectionimage',
            name='processed_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='inspections/processed/%Y/%m/%d/'),
        ),
    ]
