# Generated by Django 6.0 on 2026-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inspections",
            "0004_alter_inspection_video_alter_inspectionimage_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detectedobject",
            name="bbox_h",
            field=models.PositiveIntegerField(
                blank=True, help_text="Bounding box height in pixels.", null=True
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="bbox_w",
            field=models.PositiveIntegerField(
                blank=True, help_text="Bounding box width in pixels.", null=True
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="bbox_x",
            field=models.PositiveIntegerField(
                blank=True, help_text="Top-left X coordinate in pixels.", null=True
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="bbox_x1",
            field=models.PositiveIntegerField(
                blank=True, help_text="Minimum X coordinate in pixels.", null=True
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="bbox_x2",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum X coordinate in pixels.", null=True
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="bbox_y",
            field=models.PositiveIntegerField(
                blank=True, help_text="Top-left Y coordinate in pixels.", null=True
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="bbox_y1",
            field=models.PositiveIntegerField(
                blank=True, help_text="Minimum Y coordinate in pixels.", null=True
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="bbox_y2",
            field=models.PositiveIntegerField(
                blank=True, help_text="Maximum Y coordinate in pixels.", null=True
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="detected_at",
            field=models.DateTimeField(
                blank=True,
                help_text="UTC timestamp when the model reported this detection.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="frame_index",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Zero-based frame index for video detections. Images default to 0.",
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="frame_timestamp_seconds",
            field=models.FloatField(
                blank=True,
                help_text="Timestamp of the video frame in seconds.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="raw_label",
            field=models.CharField(
                blank=True,
                help_text="Original class label emitted by the YOLO model.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="analysis_log",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured JSON log of detections, severity, coordinates, and timestamps.",
            ),
        ),
        migrations.AlterField(
            model_name="detectedobject",
            name="bbox_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{'x': 10, 'y': 20, 'w': 30, 'h': 40, 'x1': 10, 'y1': 20, 'x2': 40, 'y2': 60}",
            ),
        ),
        migrations.AlterField(
            model_name="detectedobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("DEBRIS", "Debris"),
                    ("FOD", "Foreign Object Debris"),
                    ("WILDLIFE_BIRDS", "Wildlife / Birds"),
                    ("BIRD", "Bird/Wildlife"),
                    ("CRACK", "Crack"),
                    ("POTHOLE", "Pothole"),
                    ("VEHICLE", "Vehicle"),
                    ("LUGGAGE", "Luggage"),
                    ("PERSONNEL", "Personnel"),
                    ("AIRCRAFT", "Aircraft"),
                    ("PERSON", "Person"),
                    ("RUNWAY", "Runway"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
