# Generated by Django 5.2.13 on 2026-04-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0005_detectedobject_bbox_h_detectedobject_bbox_w_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectedobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("DEBRIS", "Debris"),
                    ("FOD", "Foreign Object Debris"),
                    ("WILDLIFE_BIRDS", "Wildlife / Birds"),
                    ("BIRD", "Bird/Wildlife"),
                    ("CRACK", "Crack"),
                    ("POTHOLE", "Pothole"),
                    ("VEHICLE", "Vehicle"),
                    ("LUGGAGE", "Luggage"),
                    ("PERSONNEL", "Personnel"),
                    ("AIRCRAFT", "Aircraft"),
                    ("FUEL_SPILL", "Fuel Spill"),
                    ("STANDING_WATER", "Standing Water"),
                    ("TOOL_EQUIPMENT", "Tool Equipment"),
                    ("CONE_OR_BARRIER", "Cone or Barrier"),
                    ("PERSON", "Person"),
                    ("RUNWAY", "Runway"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
