# Generated by Django 5.2.13 on 2026-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0006_alter_detectedobject_object_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="processed_video",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="inspections/processed_videos/%Y/%m/%d/",
            ),
        ),
    ]
